### PR TITLE
<INCLUDES> needs to be explicitly listed here 

### PR DESCRIPTION
**Pull request by autopulated**
(for some reason everything worked OK without this with older CMake versions)

Need to verify how backwards compatible this is with old CMake versions before merging.

### CODE REVIEW

**Comment by 0xc0170** [comment]
What's the version you are testing?

**Comment by autopulated** [comment]
This is for CMake >= 3.4

so turns out this breaks in < 3.4.0. It's easy enough to test the version and do the right thing, but I'm trying to figure out why exactly this is necessary, in case there's something deeper going on.

AFAICS there's no mention of this in any cmake changelog or issue

**Comment by PrzemekWirkus** [comment]
Hi,
When I use latest CMake (v3.4) I have building issues with it:

```
$  cmake --version
cmake version 3.4.0-rc1

CMake suite maintained and supported by Kitware (kitware.com/cmake).
```

Issues while building with `frdm-k64f-gcc` target:

```
$ yt clean
$yt build
```

```
info: generate for target: frdm-k64f-gcc 0.1.3 at c:\Work\mbed-drivers\yotta_targets\frdm-k64f-gcc
GCC version is: 4.8.4
-- The ASM compiler identification is GNU
-- Found assembler: C:/Work/toolchains/gcc_arm_4_8/4_8_2014q3/bin/arm-none-eabi-gcc.exe
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Work/mbed-drivers/build/frdm-k64f-gcc
[6/169] Building CXX object ym/uvisor-lib/source/CMakeFiles/uvisor-lib.dir/benchmark.cpp.o
FAILED: C:\Work\toolchains\gcc_arm_4_8\4_8_2014q3\bin\arm-none-eabi-g++.exe   -fno-exceptions -fno-unwind-tables -ffunction-sections -fdata-sections -Wall -Wextra -fno-rtti -fno-threadsafe-statics -mcpu=cortex-m4 -mthumb -D__thumb2__ -Os -g -gdwarf-3 -DNDEBUG   -DTOOLCHAIN_GCC -DTOOLCHAIN_GCC_ARM -DMBED_OPERATORS -DCPU_MK64FN1M0VMD12 -DTARGET_K64F -include "c:/Work/mbed-drivers/build/frdm-k64f-gcc/yotta_config.h" -MMD -MT ym/uvisor-lib/source/CMakeFiles/uvisor-lib.dir/benchmark.cpp.o -MF ym/uvisor-lib/source/CMakeFiles/uvisor-lib.dir/benchmark.cpp.o.d -o ym/uvisor-lib/source/CMakeFiles/uvisor-lib.dir/benchmark.cpp.o -c C:/Work/mbed-drivers/yotta_modules/uvisor-lib/source/benchmark.cpp
C:/Work/mbed-drivers/yotta_modules/uvisor-lib/source/benchmark.cpp:17:35: fatal error: uvisor-lib/uvisor-lib.h: No such file or directory
 #include "uvisor-lib/uvisor-lib.h"
                                   ^
compilation terminated.
[6/169] Building CXX object ym/uvisor-lib/source/CMakeFiles/uvisor-lib.dir/error.cpp.o
FAILED: C:\Work\toolchains\gcc_arm_4_8\4_8_2014q3\bin\arm-none-eabi-g++.exe   -fno-exceptions -fno-unwind-tables -ffunction-sections -fdata-sections -Wall -Wextra -fno-rtti -fno-threadsafe-statics -mcpu=cortex-m4 -mthumb -D__thumb2__ -Os -g -gdwarf-3 -DNDEBUG   -DTOOLCHAIN_GCC -DTOOLCHAIN_GCC_ARM -DMBED_OPERATORS -DCPU_MK64FN1M0VMD12 -DTARGET_K64F -include "c:/Work/mbed-drivers/build/frdm-k64f-gcc/yotta_config.h" -MMD -MT ym/uvisor-lib/source/CMakeFiles/uvisor-lib.dir/error.cpp.o -MF ym/uvisor-lib/source/CMakeFiles/uvisor-lib.dir/error.cpp.o.d -o ym/uvisor-lib/source/CMakeFiles/uvisor-lib.dir/error.cpp.o -c C:/Work/mbed-drivers/yotta_modules/uvisor-lib/source/error.cpp
C:/Work/mbed-drivers/yotta_modules/uvisor-lib/source/error.cpp:17:35: fatal error: uvisor-lib/uvisor-lib.h: No such file or directory
 #include "uvisor-lib/uvisor-lib.h"
                                   ^
compilation terminated.
...
```

**Comment by PrzemekWirkus** [comment]
There are no issues with CMake v3.1.

**Comment by autopulated** [comment]
This is the relevant change in CMake: https://github.com/Kitware/CMake/commit/c736de7b284ecc93bac48106e88417e0e6c92ad6

**Comment by autopulated** [comment]
@PrzemekWirkus did you test with this PR? I'm pretty sure this PR as it currently is will break things in CMake v3.1, but will work fine in CMake >= 3.4

**Comment by PrzemekWirkus** [comment]
@autopulated I've created issue related to this here: https://github.com/ARMmbed/yotta/issues/486.
I did not test with this PR yet, I will.

PS: Is there a way to have support for both CMake 3.1 and 3.4 ?

**Comment by autopulated** [comment]
@PrzemekWirkus yes there is, I will update this PR so that it is compatible with everything before merging, obviously ;)
